Objetivo
pablo1mc315/iv_pablomc pull request #1
Opened 2022-09-19 10:59 UTC by pablo1mc315

2022-09-19 12:49 UTC, JJ commented
Tienes que comprobar que has hecho todo lo que dice en la lista de comprobación del objetivo, y ponerlo en el cuerpo del PR

2022-09-20 09:36 UTC, pablo1mc315 commented
* [x] ¿Se trata de un problema real del que se tenga conocimiento personal? Sí, ya que la mayoría de la población, sobre todo aquellos que tienen una economía menos flexible, normalmente les cuesta llegar a fin de mes. Por tanto, si se pudiera realizar una predicción precisa de los gastos en función a ciertos precios, sería más fácil poder controlarlos y ahorrar o, al menos, no gastar el dinero en ciertos "lujos" que luego puedan suponernos una subida inesperada de los gastos por la subida de los precios.
* [x] ¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube? Sí, ya que para poder realizar predicciones e informes precisos acerca de los gastos debemos tener una serie de datos en la nube sobre los que hacer dichos informes y predicciones según vayan variando los precios, mercados, etc.
* [x] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse sólo almacenando y buscando? Sí, ya que la idea de realizar predicciones e informes va mucho más allá de simplemente almacenar los datos de los precios y añadir o quitar gastos. Esto le da una funcionalidad extra, lo cual también puede beneficiar a ciertas empresas que inviertan en nuestra aplicación a cambio de obtener sus datos para sus propios informes de negocio.
* [x] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el `README`?

2022-09-20 09:37 UTC, pablo1mc315 commented
@JJ ya se ha añadido la lista de comprobación, por lo que ya puede volver a revisarlo

2022-09-20 10:29 UTC, JJ commented
> @JJ ya se ha añadido la lista de comprobación, por lo que ya puede volver a revisarlo

Lo tienes que poner en el cuerpo del PR, no en un comentario.

2022-09-20 10:36 UTC, JJ requested changes
Está muy cerca, pero tendrás que hacer una serie de aclaraciones y entender lo que implican las elecciones que has tomado.

2022-09-20 10:36 UTC, JJ commented on README.md
> +Nuestro problema a resolver es la dificultad para ahorrar dinero y evitar gastos innecesarios que tiene la mayoría de la población, sobre todo aquellas personas que no disponen de unos ingresos muy e
Estás planteando un problema que no se puede resolver con un programa. Si la gente no ahorra, seguirá sin ahorrar. Usando design thinking, puedes intentar llegar a un aspecto del problema que sí se pueda solucionar mediante un programa, pero en general, es complicado partir de ahí.

2022-09-20 10:36 UTC, JJ commented on README.md
> +  - Todos aquellos inversores a los que se les pueden vender los datos de la aplicación para saber cuales son los principales gastos, en general, de los usuarios 	dependiendo de la epoca, la situacio
No puedes vender datos personales, lo sabes, ¿no?

2022-09-20 10:36 UTC, JJ commented on README.md
> +Para solucionar este problema, se propone el desarrollo de un software en la nube que, principalmente, se encargue de predecir los gastos del usuario mediante algoritmos de aprendizaje a partir de lo
Estás diciendo que la gente gasta mucho porque no sabe predecir sus gastos. Si no sabe predecir sus gastos, ese es el problema, no que no ahorre. 

Ten en cuenta que tienes que programar tú el algoritmo de predicción,  porque tienes que testear la lógica de negocio. Y para testearlo, estás hablando de testear un algoritmo que no va a ser exacto. Confío en que sepas hacerlo, pero sólo quiero aclararte lo que implica poner una lógica de negocio determinada.

2022-09-20 10:36 UTC, JJ commented on README.md
> +Además de esta principal funcionalidad, nuestra aplicación en la nube podría tener otras funcionalidades complementarias que ayuden al usuario, como por ejemplo, permitirle modificar la cantidad de d
Una aplicacién resuelve un problema. Si esas funcionalidades ayudan a resolver el problema, se incluyen. Si no, pues no.

2022-09-22 16:21 UTC, pablo1mc315 commented
@JJ he intentado elaborar otra nueva idea que enfoque el proyecto con una visión más correcta

2022-09-22 17:53 UTC, JJ approved these changes
Voy a aprobar, pero:
1. Por favor mira algoritmos _reales_ de recomendación, como el *a priori* de Agrawal. Y una vez que lo veas, tendrás que ver sobre qué lo vas a aplicar.
2. Tienes que usar datos lo más reales posibles. IMDB exporta su base de datos, y seguramente habrá algún API que puedas usar. Seguramente en kaggle habrá también alguna. 

Recuerda que tienes que programar tú la lógica de negocio y que tendrás que usar los ejemplos descargados del API.

2022-09-23 10:48 UTC, pablo1mc315 commented
He añadido las capturas de pantalla correspondientes a la configuración del repositorio y la obtención de las claves pública y privada, y lo he enlazado todo en el README. Mergeo el PR y comienzo con el objetivo 1

2022-09-23 10:48 UTC, merged