Objetivo 1
pablo1mc315/iv_pablomc pull request #2
Opened 2022-09-29 11:55 UTC by pablo1mc315

2022-10-05 06:19 UTC, JJ requested changes
Por favor, revisa tranquilamente los conceptos correspondientes y elabora un poco más las HUs y los milestones.

2022-10-05 06:19 UTC, JJ commented on docs/historias-usuario.md
> +Manuel, debido a que consume gran cantidad de películas, necesita que la aplicación le recomiende nuevos títulos que se acaben de estrenar o películas que no haya visto aún, para no aburrirse viendo
Necesitas precisar más esta historia de usuario. Películas nuevas son simplemente películas que no ha visto, y como tal se resuelve con una simple búsqueda.

2022-10-05 06:19 UTC, JJ commented on docs/historias-usuario.md
> +Maite, debido a su carga de trabajo, desea ver documentales pero que no duren demasiado, por lo cual, le gustaría poder filtrar los títulos que aparecen para que solo aparezcan documentales de histor
Una vez más, se resuelve sólo con una búsqueda. Las historias de usuario tienen que hacer referencia a la lógica de negocio.

2022-10-05 06:19 UTC, JJ commented on docs/historias-usuario.md
> +* [[HU2] Ángela quiere que le aparezcan como recomendaciones las continuaciones de la saga que está viendo.](https://github.com/pablo1mc315/iv_pablomc/issues/5)
Esto es una simple búsqueda. Si es parte de otra HU, podría ser parte del contexto.

2022-10-05 06:19 UTC, JJ commented on docs/historias-usuario.md
> +* [[HU3] Manuel quiere ver una película en concreto.](https://github.com/pablo1mc315/iv_pablomc/issues/6)
Absolutamente nada que ver con la lógica de negocio. Ni siquiera plantea un problema.

2022-10-05 06:19 UTC, JJ commented on docs/milestones.md
> +* [[M0] Modelo de la estructura de datos para almacenar las películas.](https://github.com/pablo1mc315/iv_pablomc/milestone/1)
"Modelo de la estructura de datos" ni siquiera es un concepto. "Almacenar" es un detalle de implementación.
En cualquier caso, no es un producto. Por favor, consulta el guión actualizado y la presentación.

2022-10-05 06:19 UTC, JJ commented on docs/milestones.md
> +* [[M1] Creación de librerías que permitan obtener información de las películas.](https://github.com/pablo1mc315/iv_pablomc/milestone/2)
Los productos deben ponerse de forma precisa. "Librerías" es más de una. Por otro lado, debe especificarse qué contienen esas "librerías". ¿Será la lógica de negocio?

2022-10-05 06:19 UTC, JJ commented on docs/milestones.md
> +Diseño y creación de una o varias librerías que nos permitan tanto obtener los datos de la base de datos diseñada en el M0 para trabajar con ellos, como insertar los datos en ella cuando se añada una
¿Qué haría que fuera una sola? ¿Qué haría que fueran varias?

2022-10-05 06:19 UTC, JJ commented on docs/milestones.md
> +* [[M2] Implementación de la lógica de negocio.](https://github.com/pablo1mc315/iv_pablomc/milestone/3)
¿En cuál de las librerías de antes? ¿Cómo puede haber librerías sin lógica de negocio?

2022-10-05 06:19 UTC, JJ commented on docs/milestones.md
> +* [[M3] Implementación del sistema de búsqueda de películas.](https://github.com/pablo1mc315/iv_pablomc/milestone/4)
¿La lógica de negocio no busca películas? ¿Qué hace entonces? Si te estás refiriendo a una HU concreta que vaya más allá del producto mínimo, acláralo.

2022-10-06 11:30 UTC, pablo1mc315 commented
@JJ he modificado las HU y los milestones conforme a lo que me ha dicho. Listo para revisión :)

2022-10-06 18:35 UTC, JJ requested changes
Revisa los milestones como hemos hablado esta mañana; también lo que te comento de HUs.

2022-10-06 18:35 UTC, JJ commented on docs/historias-usuario.md
> +* [[HU1] Ángela quiere que le aparezcan como recomendaciones las continuaciones de la saga que está viendo.](https://github.com/pablo1mc315/iv_pablomc/issues/5)
No tengo muy claro que esto sea realmente un problema. Y si lo es, no entiendo muy bien donde estaría la lógica de negocio. Pero si tu lo ves, no tengo mucho problema.

2022-10-06 18:35 UTC, JJ commented on docs/milestones.md
> +* [[M0] Diseño de la estructura de datos que represente los datos de la aplicación.](https://github.com/pablo1mc315/iv_pablomc/milestone/1)
"Diseño" no es un producto. Por favor, formula los milestones como producto.

2022-10-06 18:35 UTC, JJ commented on docs/personas.md
> +## Manuel Vallejo
¿Todos estos tienen HU?

2022-10-07 07:25 UTC, pablo1mc315 commented on docs/historias-usuario.md
> +* [[HU1] Ángela quiere que le aparezcan como recomendaciones las continuaciones de la saga que está viendo.](https://github.com/pablo1mc315/iv_pablomc/issues/5)
La lógica de negocio está en la recomendación, Por ejemplo, si estoy viendo una saga larga que tiene 7-8 películas, me gustaría que una vez vista la película 4, me aparezca en mis recomendaciones la película 5, y no la 7 o la 8. Esto evitaría tener que buscarla, cuando el sistema de recomendaciones ya podría solucionarlo.

2022-10-07 07:27 UTC, pablo1mc315 commented
@JJ ya he revisado el M0 y he borrado las personas que aparecían en las HU que eliminé la revisión anterior. Listo para revisión

2022-10-07 08:44 UTC, JJ commented on docs/historias-usuario.md
> +* [[HU1] Ángela quiere que le aparezcan como recomendaciones las continuaciones de la saga que está viendo.](https://github.com/pablo1mc315/iv_pablomc/issues/5)
Creo que no tiene mucha lógica de negocio eso. Podría ser un issue, que te diga que hay que prever que las pelis están almacenadas para tener esto en cuenta.

2022-10-07 08:45 UTC, JJ requested changes
Mira lo que te he comentado sobre la historia de usuario, y como ya he dicho en clase, una estructura de datos no es un producto. Menciona de forma precisa cuál es el producto que va a contener esa estructura de datos y qué lo haría viable.

2022-10-07 11:19 UTC, pablo1mc315 commented on docs/historias-usuario.md
> +* [[HU1] Ángela quiere que le aparezcan como recomendaciones las continuaciones de la saga que está viendo.](https://github.com/pablo1mc315/iv_pablomc/issues/5)
A lo que me refiero no es a que las pelis estén almacenadas, eso por supuesto que debe ser así para que pueda recomendarlas y lo pondré en un issue en el futuro, pero me refería a la recomendación en si, es decir, que cuando acabes una película de una saga te muestre como recomendación la siguiente, no otra, para que te sea mas fácil y cómo y no tengas que buscar esa película en la app, esa es la lógica de negocio

2022-10-07 11:24 UTC, pablo1mc315 commented
@JJ he vuelto a modificar el M0, y creo que tengo ya la idea un poco más clara con respecto a ello. Listo para revisión

2022-10-07 15:14 UTC, JJ requested changes
Deja sólo lo que sea realmente una historia de usuario, y no incluyas en la secuencia de milestones algo que necesitaría más pasos intermedios.

2022-10-07 15:14 UTC, JJ commented on docs/historias-usuario.md
> +* [[HU1] Ángela quiere que le aparezcan como recomendaciones las continuaciones de la saga que está viendo.](https://github.com/pablo1mc315/iv_pablomc/issues/5)
No, no lo es porque es un simple cálculo. Puede ser un issue, como te digo.

2022-10-07 15:14 UTC, JJ commented on docs/milestones.md
> +* [[M4] Implementación de la interfaz de usuario.](https://github.com/pablo1mc315/iv_pablomc/milestone/5)
No va a dar tiempo, y si diera no va a estar habrá que hacer muchas cosas antes. Entre el sistema de la recomendación y la interfaz del usuario, ¿no habrá algo más que hacer?

2022-10-08 17:50 UTC, pablo1mc315 commented
@JJ listo para revisión. He eliminado el M4 que se refería a la interfaz de usuario ya que me dijo que no iba a dar tiempo a implementarlo y en su lugar he añadido otro que creo que, en este caso, iría entre el sistema de recomendaciones y la interfaz de usuario, como es el sistema de visualización de películas. Del mismo modo, he modificado la HU1 por otra que creo algo más adecuada a la lógica de negocio de un sistema de recomendaciones :)

2022-10-09 16:22 UTC, JJ commented
> @JJ listo para revisión. He eliminado el M4 que se refería a la interfaz de usuario ya que me dijo que no iba a dar tiempo a implementarlo y en su lugar he añadido otro que creo que, en este caso, iría entre el sistema de recomendaciones y la interfaz de usuario, como es el sistema de visualización de películas. Del mismo modo, he modificado la HU1 por otra que creo algo más adecuada a la lógica de negocio de un sistema de recomendaciones :)

¿De qué forma la *visualización* de películas *no* es el interfaz de usuario? Hará falta un interfaz, pero no de usuario.

2022-10-09 16:27 UTC, JJ requested changes
Creo que tendrías que darle una vuelta a los conceptos de lógica de negocio, y también a la secuencia de hitos que se alcanzan en la asignatura.

2022-10-09 16:27 UTC, JJ commented on docs/historias-usuario.md
> +* [[HU0] Manuel quiere ver películas recien estrenadas.](https://github.com/pablo1mc315/iv_pablomc/issues/3)
No entiendo muy bien qué tienen de especial las películas *recién* estrenadas. No mencionéis en las historias de usuario nada que sea irrelevante a la lógica de negocio.

2022-10-09 16:27 UTC, JJ commented on docs/historias-usuario.md
> +Ángela, las pocas veces que accede a nuestra aplicación, suele pasarse todo el día viendo películas. Para ello, la aplicación debe basarse en sus gustos y mostrarle películas que pertenezcan a sagas
De veras que no acabo de verlo. ¿Tu modelo del problema va a incluir el hecho de que una película pertenezca a una saga *larga*? Si lo hace, ¿la lógica de negocio es más complicada que "si es de una saga y ha visto las otras de la saga, hay que recomendarla"?

2022-10-09 16:27 UTC, JJ commented on docs/milestones.md
> +Diseñar una estructura de datos que nos permita almacenar las películas con todos los datos necesarios de cada una (título, género, fecha de salida, duración, listado de actores principales, si ya se
No menciones cuales son los datos necesarios. No puedes poner detalles de implementación.

2022-10-09 16:27 UTC, JJ commented on docs/milestones.md
> +* [[M4] Implementación de una funcionalidad que permita ver películas al usuario.](https://github.com/pablo1mc315/iv_pablomc/milestone/5)
Por favor, revisa lo que se busca en la asignatura y cuál es el sentido que tienen estos hitos. Revisa también los objetivos que hay en la misma, que como ya os dije, tendrán que alinearse con los hitos de tu proyecto.

2022-10-10 09:52 UTC, pablo1mc315 commented
@JJ he eliminado de cada milestone lo que creo que se corresponden con detalles de implementación y he modificado el M4, así como las HU por algo que creo que se adecúa más a la definición de una Historia de Usuario. Listo para revisión

2022-10-10 12:38 UTC, JJ approved these changes
:+1: Si clarificas un poco más antes del siguiente, mejor.

2022-10-10 12:38 UTC, JJ commented on docs/historias-usuario.md
> +* [[HU1] Ángela quiere ver películas en las que aparezcan los actores que más le gustan.](https://github.com/pablo1mc315/iv_pablomc/issues/5)
¿Esto afecta a la lógica de negocio? ¿O es simplemente buscar?

Si no afecta a la lógica de negocio, no es una historia de usuario, sino una simple forma de desambiguar los modelos. Si afecta, tendrás que decir de forma precisa cómo va a hacerlo, pero si no tiene lógica de negocio específica será simplemente una forma de cualificar la #3

2022-10-10 12:38 UTC, JJ commented on docs/historias-usuario.md
> +* [[HU0] Manuel quiere que la aplicación le recomiende películas en función a sus géneros favoritos.](https://github.com/pablo1mc315/iv_pablomc/issues/3)
No hay HUs número 0. ¿Por qué tendría que haberlas? En los milestones, el 0 es el previo a cualquier creación de código. Pero aquí *todas* afectarán al código.

2022-10-10 12:38 UTC, JJ commented on docs/historias-usuario.md
> +Ángela quiere ver películas en las que aparezcan sus actores favoritos en función a las películas que ya ha visto, por lo que quiere que le aparezcan como recomendaciones películas de los mismos que
OK, parece que tiene cierto sentido, aunque no lo acabo de ver como una HU separada. Quizás una para algún PMV posterior.

2022-10-10 18:10 UTC, merged