[IV-22-23] Objetivo 3
pablo1mc315/iv_pablomc pull request #29
Opened 2022-11-02 17:05 UTC by pablo1mc315

# Lista de comprobación

* [ ]  ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos
anteriores?
* [ ]  ¿Se ha desarrollado el fichero para las tareas a partir de un
   issue?
* [ ]  ¿Ese issue está asignado a un milestone?
* [ ] ¿El milestone incluye, entre sus productos mínimamente viables, la
  existencia de herramientas que permitan automatizar tareas?
* [ ]  ¿Hemos justificado correctamente en caso de elegir un gestor de
   dependencias el que se use como gestor de tareas?
* [ ]  ¿El PR, que también es un issue, está asignado al mismo milestone?
* [ ] ¿La tarea `check` efectivamente comprueba la sintaxis de los fuentes
  existentes?

2022-11-03 12:35 UTC, pablo1mc315 commented
@JJ listo para revisión!

2022-11-03 13:15 UTC, JJ requested changes
Tienes que poner los criterios que has usado para buscar, y qué requisitos tienen que seguir. Por otro lado, las listas que pones ni son exhaustivas ni correctas, incluyendo herramientas que no corresponden al concepto (y no se sabe si a los criterios porque no los has puesto)

2022-11-03 13:15 UTC, JJ commented on docs/gestor-dependencias.md
> +Es una librería JavaScript que nos permite aislar mediante módulos los componentes de nuestra aplicación cliente y resolver las dependencias de estos mismos. Sus principales características son la ca
No es un gestor de dependencias. Por favor, revisa el concepto y pon sólo las que cumplan ese requisito.

2022-11-03 13:15 UTC, JJ commented on docs/gestor-dependencias.md
> +Es un gestor de paquetes que funciona en el navegador. Se trata de un gestor de paquetes de JavaScript gestión automática similar a RequireJS. Todas sus dependencias son introducidas en un único arch
¿Tú trabajar en el navegador?
No se trata de que me pongáis lo que os aparezca en google, sino los criterios que habéis usado para elegir uno y por qué.

2022-11-03 13:15 UTC, JJ commented on docs/gestor-tareas.md
> +### Bun
No es estrictamente un task runner.

2022-11-03 17:49 UTC, pablo1mc315 commented
He eliminado los que, efecitvamente, no son gestores de dependencias (como RequireJS y JamJS que hemos comentado en clase) y he estado investigando un poco más. He añadido a la documentación pNpm, el cual me parece también una opción viable para el proyecto ya que, como se indica, por ejemplo, en [Snyk Advisor](https://snyk.io/advisor/npm-package/pnpm), es muy buena opción. También he encontrado otros como "Volo" o "EnderJS", pero están muy desactualizados o tienen problemas de seguridad, por lo que los descarto como opciones.

En cuanto al gestor de tareas, he eliminado bun, ya que tampoco es un gestor de tareas como tal como usted me indica y creo que los principales en cuanto a JavaScript se refiere son Grunt y Gulp, además de make.

Listo para revisión @JJ

2022-11-04 09:18 UTC, pablo1mc315 commented
@JJ he establecido una lista de criterios para cada herramientas, añadiendo información acerca de cada una de ellas y comparando ventajas e inconvenientes de cada una respecto a las otras y respecto a la lista de criterios establecidos, además de justificar un poco más las decisiones tomadas. Listo para revisión!

2022-11-07 14:13 UTC, JJ requested changes
Los criterios no hay que ponerlos porque "hay que poner criterios". Hay que ponerlos porque son lo que has usado para elegir uno u otro.
A estas alturas está claro que vas a poner lo que sea y que ya te habías decantado por uno u otro, pero por lo menos trata de ser coherente en lo que escribes.

2022-11-07 14:13 UTC, JJ commented on docs/gestor-dependencias.md
> +Es un gestor de dependencias que usa los formatos de configuración de npm pero, a diferencia de este y de Yarn, ahorra mucho espacio en disco proporcional a la cantidad de proyectos y dependencias y
De veras que no hacen falta estas descripciones. Decid de los criterios que tengáis los que cumplen y no cumplen y ya está.

2022-11-07 14:13 UTC, JJ commented on docs/gestor-tareas.md
> +Viene incorporado en NodeJS y, como ya se ha explicado en #26, funciona tanto como gestor de tareas como gestor de dependencias.
Es muy limitado como gestor de tareas.

2022-11-07 14:13 UTC, JJ commented on docs/gestor-tareas.md
> +Me he decantado por make, ya que es una herramienta que he utilizado a lo largo de la carrera y nunca le he sacado todo su potencial. Además, tiene una gran cantidad de documentación al ser el más an
Los criterios tenéis que establecerlos de antemano, no a posteriori. Si no parece simplemente que has puesto cosas, y elegido el que pensabas elegir desde el principio. Si la documentación o cualquier otro criterio es para ti lo importante, pon claramente cuales son los criterios.

2022-11-07 14:13 UTC, JJ commented on Makefile
> +	node --check $(SRC)/film.js $(SRC)/user.js
Ya puestos, deberías tratar de que comprobara *todos* los ficheros cuando se añadan, no sólo estos...

2022-11-07 14:13 UTC, JJ commented on docs/gestor-dependencias.md
> +Es un gestor dependencias de JavaScript, basado en npm, que está muy enfocado en la velocidad y la seguridad, muy rápido y muy fácil de usar. Además, devuelve un feedback al usuario bastante amigable
De veras, ¿por qué escribís esto? Si no fuera un gestor de dependencias de javascript, ¿qué hacía aquí? ¿Por qué ponéis el panfleto publicitario? ¿Eso ayuda a elegir a este y no otro? ¿Los otros no están enfocados a la velocidad?

2022-11-07 14:13 UTC, JJ commented on docs/gestor-dependencias.md
> +Tenía la duda entre npm y Yarn, ya que el segundo es más moderno y soluciona problemas que se encontraron en el primero, pero, finalmente, me he decantado por npm ya que las diferencias que hay entre
¿Según qué criterios de los que has puesto? Si pones criterios, tendrás que seguirlos, ¿no?

2022-11-07 14:13 UTC, JJ commented on docs/gestor-tareas.md
> +Viene incorporado en NodeJS y, como ya se ha explicado en #26, funciona tanto como gestor de tareas como gestor de dependencias. Hay dos tipos de tareas con npm, tareas integradas (las que son comune
Estos enlaces sólo funcionan el commits e issues. Tendrás que poner aquí el enlace completo.
¿Qué diferencia hay entre las tareas integradas y las propias?

2022-11-07 14:13 UTC, JJ commented on docs/gestor-tareas.md
> +Se basa en el entorno en tiempo de ejecución NodeJS de JavaScript. Guarda toda la información en el archivo gruntfile.js, donde se incluye el código original con el que se integran y configuran los m
¿En qué creéis que contribuye este párrafo a que yo evalúe si habéis alcanzado el objetivo o no?

2022-11-07 14:13 UTC, JJ commented on docs/gestor-tareas.md
> +Me he decantado por make, ya que es una herramienta muy utilizada (con la que, además, ya he trabajado anteriormente) y permite muchas otras opciones además de ejecutar tareas de forma muy eficiente.
"muy utilizada" no es ninguno de los tres criterios que has establecido. De hecho, ¿cómo permite gestionar tareas de javascript?

2022-11-08 10:37 UTC, pablo1mc315 commented on docs/gestor-tareas.md
> +Me he decantado por make, ya que es una herramienta que he utilizado a lo largo de la carrera y nunca le he sacado todo su potencial. Además, tiene una gran cantidad de documentación al ser el más an
Imagino que este comentario me lo puso hace días, cuando GitHub no le dejaba enviarme la revisión, puesto que en posteriores commits ya añadí la lista de criterios y me sale como 'outdated'

2022-11-08 10:45 UTC, JJ commented on docs/gestor-tareas.md
> +Me he decantado por make, ya que es una herramienta que he utilizado a lo largo de la carrera y nunca le he sacado todo su potencial. Además, tiene una gran cantidad de documentación al ser el más an
cierto.

2022-11-08 23:25 UTC, pablo1mc315 commented
@JJ listo para revisión. He modificado las descripciones de los gestores para que se ajusten a los criterios establecidos y para que sea más fácil compararlos según estos, y he eliminado datos innecesarios de las mismas que no influyen para la elección.

Además de eso, como indico en #32, he visto conveniente añadir un linter al proyecto, en este caso ESLint, ya que con node resultaba demasiado tedioso el proceso de comprobar todos los archivos que pudiese haber en la carpeta src, pues node solo permite realizar la comprobación uno a uno.

2022-11-09 06:29 UTC, JJ commented
> @JJ listo para revisión. He modificado las descripciones de los gestores para que se ajusten a los criterios establecidos y para que sea más fácil compararlos según estos, y he eliminado datos innecesarios de las mismas que no influyen para la elección.
> 
> Además de eso, como indico en #32, he visto conveniente añadir un linter al proyecto, en este caso ESLint, ya que con node resultaba demasiado tedioso el proceso de comprobar todos los archivos que pudiese haber en la carpeta src, pues node solo permite realizar la comprobación uno a uno.

Os he insistido mucho en que uséis productos mínimamente viables. Lo que te comenté sobre todos los ficheros era 
1. Una sugerencia
2. Fácilmente soluble con Make
3. Algo que podías haber añadido como requisito para elegir un gestor de tareas

Así que quita el linter, que no es lo que se pide en este objetivo.

2022-11-09 06:32 UTC, JJ requested changes
En esta asignatura se valora el trabajo autónomo, y por tanto las coincidencias en contenido entre varias entregas de diferentes estudiantes se puntúan muy negativamente, cuanto más si son erróneas (siempre lo son).

2022-11-09 06:46 UTC, pablo1mc315 commented
No he puesto un linter porque alguien lo haya puesto o no, lo he hecho porque investigando ayer era la unica manera que encontre de hacerlo (puedo adjuntarle la documentacion donde lo vi si lo desea), ya que con node no es posible hacer `node --check ./src/*js` puesto que esta orden da error ya que no detecta el * como un nonbre de fichero, cosa que puedo demostrarle en clase.

Además, también usted mencionó el linter en clase, así que me pareció buena opción su uso. Si no lo cree conveniente lo elimino, pero le aseguro que no me he guiado por el proyecto de nadie y menos después de lo que usted me dijo en clase. @JJ

2022-11-09 06:57 UTC, JJ commented
> No he puesto un linter porque alguien lo haya puesto o no, lo he hecho porque investigando ayer era la unica manera que encontre de hacerlo (puedo adjuntarle la documentacion donde lo vi si lo desea), ya que con node no es posible hacer `node --check ./src/*js` (esta orden da error ya que no detecta el * como un nombre de fichero, cosa que puedo demostrarle en clase).
> 
> Además, también usted mencionó el linter en clase, así que me pareció buena opción su uso. Si no lo cree conveniente lo elimino, pero le aseguro que no me he guiado por el proyecto de nadie y menos después de lo que usted me dijo en clase. @JJ

No, no es el linter, que está mal de todas formas. Es por los "criterios" que no son tales criterios porque no los has usado para elegir o no algo que ya tenías elegido de antemano.

2022-11-09 07:15 UTC, pablo1mc315 commented
> No, no es el linter, que está mal de todas formas. Es por los "criterios" que no son tales criterios porque no los has usado para elegir o no algo que ya tenías elegido de antemano.

Pues volveré a darle una vuelta e intentaré olvidarme de lo que he elegido y volver a hacer todo el proceso "de nuevo" para elegir uno, pero le aseguro que no tengo ni idea de qué criterios han puesto mis compañeros ya que llevo basándome en estos mismos criterios unas dos semanas desde que empecé el objetivo 3

2022-11-09 07:46 UTC, JJ commented
Bueno es saberlo.
En todo caso estoy preparando una presentación para el viernes, en cuanto que esté te la enlazo.

2022-11-09 08:02 UTC, pablo1mc315 commented
Perfecto gracias, seguiré trabajando en ello y le solicito revisión cuando lo tenga

2022-11-09 08:08 UTC, JJ commented
[Aquí está](https://jj.github.io/IV/preso/criterios-herramientas.html). Es lo mismo que hay en el guión, de todas formas (también he adaptado este un poco)

2022-11-11 08:36 UTC, pablo1mc315 commented
@JJ Listo para revisión.

2022-11-11 15:28 UTC, pablo1mc315 commented
@JJ Listo para revisión

2022-11-11 16:40 UTC, JJ approved these changes
Revisad por favor lo que escribís a ver si describe con precisión lo que queréis decir. En particular "tareas con javascript" no parece que sea un concepto adecuado (entre otras cosas porque arrancar un test runner, por ejemplo, será una herramienta de línea de órdenes)

2022-11-11 16:40 UTC, JJ commented on Makefile
> +	$(foreach fichero, $(lista_ficheros), node --check $(fichero);)
👏 
(creo que habría sido más fácil que usaras un glob)

2022-11-11 16:40 UTC, JJ commented on docs/gestor-tareas.md
> +- Obligatoriamente, deberá permitir gestionar tareas de JavaScript.
No son tareas de Javascript.

2022-11-11 17:40 UTC, merged